"""
TheAltText — Automated Audit & PDF Report Generation Service
Monthly automated audits with professional PDF/HTML report generation.
Chain of custody tracking for compliance documentation.
"""
import logging
import io
import json
import time
from typing import Dict, List, Optional
from datetime import datetime, timezone
from jinja2 import Template
from weasyprint import HTML

logger = logging.getLogger(__name__)

# Professional HTML report template
REPORT_HTML_TEMPLATE = """
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>{{ title }}</title>
<style>
  @import url('https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700&display=swap');
  * { margin: 0; padding: 0; box-sizing: border-box; }
  body { font-family: 'Inter', sans-serif; color: #1a1a1a; line-height: 1.6; padding: 40px; }
  .header { text-align: center; margin-bottom: 40px; padding-bottom: 20px; border-bottom: 3px solid #b07d3a; }
  .header h1 { font-size: 28px; color: #1a1a1a; margin-bottom: 8px; }
  .header .subtitle { font-size: 14px; color: #666; }
  .header .brand { font-size: 12px; color: #b07d3a; margin-top: 8px; }
  .meta-box { background: #f8f6f3; border: 1px solid #e8e0d4; border-radius: 8px; padding: 20px; margin-bottom: 30px; }
  .meta-grid { display: grid; grid-template-columns: 1fr 1fr; gap: 12px; }
  .meta-item { font-size: 13px; }
  .meta-label { font-weight: 600; color: #666; }
  .score-section { text-align: center; margin: 30px 0; }
  .score-circle { display: inline-block; width: 120px; height: 120px; border-radius: 50%; line-height: 120px; font-size: 36px; font-weight: 700; color: white; }
  .score-high { background: linear-gradient(135deg, #3a7d3a, #2e632e); }
  .score-medium { background: linear-gradient(135deg, #b07d3a, #967820); }
  .score-low { background: linear-gradient(135deg, #c46356, #b0443a); }
  .score-label { display: block; margin-top: 8px; font-size: 14px; color: #666; }
  h2 { font-size: 20px; color: #1a1a1a; margin: 30px 0 15px; padding-bottom: 8px; border-bottom: 2px solid #e8e0d4; }
  h3 { font-size: 16px; color: #333; margin: 20px 0 10px; }
  table { width: 100%; border-collapse: collapse; margin: 15px 0; font-size: 13px; }
  th { background: #f0ebe3; color: #1a1a1a; font-weight: 600; text-align: left; padding: 10px 12px; border: 1px solid #e0d8cc; }
  td { padding: 8px 12px; border: 1px solid #e8e0d4; vertical-align: top; }
  tr:nth-child(even) { background: #faf8f5; }
  .severity-critical { color: #c46356; font-weight: 600; }
  .severity-major { color: #b07d3a; font-weight: 600; }
  .severity-minor { color: #666; }
  .badge { display: inline-block; padding: 2px 8px; border-radius: 4px; font-size: 11px; font-weight: 600; }
  .badge-pass { background: #e8f5e8; color: #2e632e; }
  .badge-fail { background: #fde8e5; color: #b0443a; }
  .badge-warn { background: #fef3e0; color: #967820; }
  .summary-grid { display: grid; grid-template-columns: repeat(4, 1fr); gap: 15px; margin: 20px 0; }
  .summary-card { background: #f8f6f3; border: 1px solid #e8e0d4; border-radius: 8px; padding: 15px; text-align: center; }
  .summary-number { font-size: 28px; font-weight: 700; color: #1a1a1a; }
  .summary-label { font-size: 12px; color: #666; margin-top: 4px; }
  .recommendation { background: #f0f7f0; border-left: 4px solid #3a7d3a; padding: 12px 16px; margin: 8px 0; border-radius: 0 8px 8px 0; font-size: 13px; }
  .issue-item { background: #fff; border: 1px solid #e8e0d4; border-radius: 8px; padding: 12px; margin: 8px 0; }
  .footer { margin-top: 40px; padding-top: 20px; border-top: 2px solid #e8e0d4; text-align: center; font-size: 11px; color: #999; }
  .footer a { color: #b07d3a; text-decoration: none; }
  .chain-of-custody { background: #f8f6f3; border: 1px solid #e8e0d4; border-radius: 8px; padding: 20px; margin: 20px 0; }
  .chain-item { display: flex; gap: 12px; margin: 8px 0; font-size: 13px; }
  .chain-time { font-weight: 600; color: #666; min-width: 180px; }
  @media print { body { padding: 20px; } .score-circle { -webkit-print-color-adjust: exact; print-color-adjust: exact; } }
</style>
</head>
<body>
  <div class="header">
    <h1>{{ title }}</h1>
    <div class="subtitle">WCAG {{ wcag_level }} Compliance Audit Report</div>
    <div class="brand">Generated by TheAltText — A GlowStarLabs Product | meetaudreyevans.com</div>
  </div>

  <div class="meta-box">
    <div class="meta-grid">
      <div class="meta-item"><span class="meta-label">Target URL:</span> {{ target_url }}</div>
      <div class="meta-item"><span class="meta-label">Report Date:</span> {{ report_date }}</div>
      <div class="meta-item"><span class="meta-label">WCAG Level:</span> {{ wcag_level }}</div>
      <div class="meta-item"><span class="meta-label">Report ID:</span> {{ report_id }}</div>
      <div class="meta-item"><span class="meta-label">Pages Scanned:</span> {{ pages_scanned }}</div>
      <div class="meta-item"><span class="meta-label">Audit Type:</span> {{ audit_type }}</div>
    </div>
  </div>

  <div class="score-section">
    <div class="score-circle {{ score_class }}">{{ compliance_score }}%</div>
    <span class="score-label">Overall Compliance Score</span>
  </div>

  <div class="summary-grid">
    <div class="summary-card">
      <div class="summary-number">{{ total_images }}</div>
      <div class="summary-label">Total Images</div>
    </div>
    <div class="summary-card">
      <div class="summary-number">{{ images_with_alt }}</div>
      <div class="summary-label">With Alt Text</div>
    </div>
    <div class="summary-card">
      <div class="summary-number">{{ images_missing }}</div>
      <div class="summary-label">Missing Alt Text</div>
    </div>
    <div class="summary-card">
      <div class="summary-number">{{ images_poor }}</div>
      <div class="summary-label">Poor Quality</div>
    </div>
  </div>

  <h2>Issues by Severity</h2>
  {% if critical_issues %}
  <h3 class="severity-critical">Critical Issues ({{ critical_issues|length }})</h3>
  {% for issue in critical_issues %}
  <div class="issue-item">
    <strong>WCAG {{ issue.wcag_criterion }}:</strong> {{ issue.message }}<br>
    <span style="color: #666; font-size: 12px;">Fix: {{ issue.fix }}</span>
    {% if issue.src %}<br><span style="color: #999; font-size: 11px;">Source: {{ issue.src }}</span>{% endif %}
  </div>
  {% endfor %}
  {% endif %}

  {% if major_issues %}
  <h3 class="severity-major">Major Issues ({{ major_issues|length }})</h3>
  {% for issue in major_issues %}
  <div class="issue-item">
    <strong>WCAG {{ issue.wcag_criterion }}:</strong> {{ issue.message }}<br>
    <span style="color: #666; font-size: 12px;">Fix: {{ issue.fix }}</span>
  </div>
  {% endfor %}
  {% endif %}

  {% if minor_issues %}
  <h3 class="severity-minor">Minor Issues ({{ minor_issues|length }})</h3>
  {% for issue in minor_issues %}
  <div class="issue-item">
    <strong>WCAG {{ issue.wcag_criterion }}:</strong> {{ issue.message }}<br>
    <span style="color: #666; font-size: 12px;">Fix: {{ issue.fix }}</span>
  </div>
  {% endfor %}
  {% endif %}

  <h2>Recommendations</h2>
  {% for rec in recommendations %}
  <div class="recommendation">{{ rec }}</div>
  {% endfor %}

  {% if seo_insights %}
  <h2>SEO Impact Analysis</h2>
  <table>
    <tr><th>Metric</th><th>Value</th><th>Impact</th></tr>
    {% for insight in seo_insights %}
    <tr><td>{{ insight.metric }}</td><td>{{ insight.value }}</td><td>{{ insight.impact }}</td></tr>
    {% endfor %}
  </table>
  {% endif %}

  <h2>Chain of Custody</h2>
  <div class="chain-of-custody">
    {% for entry in chain_of_custody %}
    <div class="chain-item">
      <span class="chain-time">{{ entry.timestamp }}</span>
      <span>{{ entry.action }}</span>
    </div>
    {% endfor %}
  </div>

  <div class="footer">
    <p>This report was automatically generated by <a href="https://meetaudreyevans.com">TheAltText</a> — AI-Powered ADA Compliance</p>
    <p>A <a href="https://meetaudreyevans.com">GlowStarLabs</a> Product by Audrey Evans</p>
    <p>Report generated: {{ report_date }} | Alt text analysis powered by free and open-source AI APIs</p>
  </div>
</body>
</html>
"""


async def generate_pdf_report(audit_data: Dict, report_id: str = "auto") -> bytes:
    """Generate a professional PDF report from audit data."""
    if report_id == "auto":
        report_id = f"TAT-{datetime.now(timezone.utc).strftime('%Y%m%d%H%M%S')}"

    score = audit_data.get("compliance_score", 0)
    score_class = "score-high" if score >= 80 else "score-medium" if score >= 50 else "score-low"

    issues_by_severity = audit_data.get("issues_by_severity", {})

    # SEO insights
    total_images = audit_data.get("total_images", 0)
    images_with_alt = audit_data.get("total_passes", 0)
    seo_insights = [
        {"metric": "Image Search Visibility", "value": f"{round(images_with_alt / max(total_images, 1) * 100)}%", "impact": "Direct ranking factor for Google Image Search"},
        {"metric": "Alt Text Coverage", "value": f"{images_with_alt}/{total_images}", "impact": "Each missing alt text is a lost ranking opportunity"},
        {"metric": "WCAG Compliance", "value": f"{score}%", "impact": "ADA compliance reduces lawsuit risk and improves SEO"},
    ]

    # Chain of custody
    now = datetime.now(timezone.utc)
    chain_of_custody = [
        {"timestamp": now.strftime("%Y-%m-%d %H:%M:%S UTC"), "action": "Automated scan initiated by TheAltText"},
        {"timestamp": now.strftime("%Y-%m-%d %H:%M:%S UTC"), "action": f"Scanned {audit_data.get('url', 'target URL')}"},
        {"timestamp": now.strftime("%Y-%m-%d %H:%M:%S UTC"), "action": f"Analyzed {total_images} images across page(s)"},
        {"timestamp": now.strftime("%Y-%m-%d %H:%M:%S UTC"), "action": f"Generated compliance report (ID: {report_id})"},
    ]

    template = Template(REPORT_HTML_TEMPLATE)
    html_content = template.render(
        title=f"Alt Text Compliance Audit — {audit_data.get('url', 'Website')}",
        target_url=audit_data.get("url", "N/A"),
        report_date=now.strftime("%B %d, %Y"),
        wcag_level=audit_data.get("wcag_level", "AAA"),
        report_id=report_id,
        pages_scanned=audit_data.get("pages_analyzed", 1),
        audit_type="Automated Monthly Audit",
        compliance_score=round(score),
        score_class=score_class,
        total_images=total_images,
        images_with_alt=images_with_alt,
        images_missing=audit_data.get("total_issues", 0),
        images_poor=len(issues_by_severity.get("major", [])),
        critical_issues=issues_by_severity.get("critical", []),
        major_issues=issues_by_severity.get("major", []),
        minor_issues=issues_by_severity.get("minor", []),
        recommendations=audit_data.get("recommendations", []),
        seo_insights=seo_insights,
        chain_of_custody=chain_of_custody,
    )

    # Generate PDF
    pdf_bytes = HTML(string=html_content).write_pdf()
    return pdf_bytes


async def generate_html_report(audit_data: Dict, report_id: str = "auto") -> str:
    """Generate an HTML report from audit data."""
    if report_id == "auto":
        report_id = f"TAT-{datetime.now(timezone.utc).strftime('%Y%m%d%H%M%S')}"

    score = audit_data.get("compliance_score", 0)
    score_class = "score-high" if score >= 80 else "score-medium" if score >= 50 else "score-low"
    issues_by_severity = audit_data.get("issues_by_severity", {})
    total_images = audit_data.get("total_images", 0)
    images_with_alt = audit_data.get("total_passes", 0)

    now = datetime.now(timezone.utc)

    seo_insights = [
        {"metric": "Image Search Visibility", "value": f"{round(images_with_alt / max(total_images, 1) * 100)}%", "impact": "Direct ranking factor"},
        {"metric": "Alt Text Coverage", "value": f"{images_with_alt}/{total_images}", "impact": "Lost ranking opportunities"},
        {"metric": "WCAG Compliance", "value": f"{score}%", "impact": "Lawsuit risk and SEO impact"},
    ]

    chain_of_custody = [
        {"timestamp": now.strftime("%Y-%m-%d %H:%M:%S UTC"), "action": "Scan initiated"},
        {"timestamp": now.strftime("%Y-%m-%d %H:%M:%S UTC"), "action": f"Analyzed {total_images} images"},
        {"timestamp": now.strftime("%Y-%m-%d %H:%M:%S UTC"), "action": f"Report generated (ID: {report_id})"},
    ]

    template = Template(REPORT_HTML_TEMPLATE)
    return template.render(
        title=f"Alt Text Compliance Audit — {audit_data.get('url', 'Website')}",
        target_url=audit_data.get("url", "N/A"),
        report_date=now.strftime("%B %d, %Y"),
        wcag_level=audit_data.get("wcag_level", "AAA"),
        report_id=report_id,
        pages_scanned=audit_data.get("pages_analyzed", 1),
        audit_type="Compliance Audit",
        compliance_score=round(score),
        score_class=score_class,
        total_images=total_images,
        images_with_alt=images_with_alt,
        images_missing=audit_data.get("total_issues", 0),
        images_poor=len(issues_by_severity.get("major", [])),
        critical_issues=issues_by_severity.get("critical", []),
        major_issues=issues_by_severity.get("major", []),
        minor_issues=issues_by_severity.get("minor", []),
        recommendations=audit_data.get("recommendations", []),
        seo_insights=seo_insights,
        chain_of_custody=chain_of_custody,
    )


async def schedule_monthly_audit(user_id: int, urls: List[str], wcag_level: str = "AAA") -> Dict:
    """Schedule a monthly automated audit for the given URLs."""
    # This creates the audit configuration — actual scheduling handled by Celery/cron
    audit_config = {
        "user_id": user_id,
        "urls": urls,
        "wcag_level": wcag_level,
        "frequency": "monthly",
        "next_run": datetime.now(timezone.utc).replace(day=1, hour=0, minute=0, second=0).isoformat(),
        "status": "active",
        "created_at": datetime.now(timezone.utc).isoformat(),
    }
    return audit_config
